
eureka:
  instance:
    instanceId: http://localhost:${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8003/eureka/
    
    
    
management:
  security:
    enabled: false 
    
security:
  basic:
    enabled: false  
    
 


spring : 
      datasource:
        url: jdbc:sqlserver://172.16.10.25:9094;databaseName=Supremo_102018
        username: Supuser
        password: S$up8i40
        tomcat:
          test-while-idle: true
          max-active: "500"
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jpa:
        show-sql: true
        hibernate:
          ddl-auto: update
          naming:
            strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect     

      zipkin:
        base-url : http://localhost:9411/ 
      jackson:
        serialization:
         FAIL_ON_EMPTY_BEANS : false

         
      
